Resources:
  ComicBooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "ASIN"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "ASIN"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "TB_COMIC_BOOKS"